---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
      tier: db

  template:
    metadata:
      labels:
        app: database
        tier: db

    spec:
      containers:
        - name: mysql
          image: akshaykumart/db
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
    tier: db

  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
