---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-app
      tier: webapp
  template:
    metadata:
      labels:
        app: wordpress-app
        tier: webapp
    spec:
      containers:
        - name: app
          image: akshaykumart/wordpress
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-app
spec:
  selector:
    app: wordpress-app
    tier: webapp

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  type: LoadBalancer
